### PR TITLE
fix(#patch): lido-ethereum; update snaphsots and tvl more often

### PR DESCRIPTION
**Pull request by jaimehgb**
We were only updating snapshots when there was a mint of stETH. This only happens once every 24 hours, so hourly snapshots were only being created once daily.

Had to make some readjustments to the way we take snapshots in this subgraph and the times we update TVL and revenues:
- TVL was not being updated when a deposit was made, only on daily revenue mint. **Fixed this.**
- Snaphots are not updated as a whole. Only certain parts of it at a time (tvl alone, supply side revenue alone, total revenue alone, protocol revenue alone). Since revenue only increases every 24h, taking a snapshot before then would make 0 cumulative values on revenue on the hourly snapshots. **Added all the copying cumulative values on all snapshot taking functions.**
- Total revenue was calculated by observing mint events, and then calling the oracle to fetch the last daily reward update. **I moved that to its own event handler emitted from the oracle.** Functionality is the same, but slightly more efficient and clearer to read and understand.
  - We still look for mint events to see which ones go to treasury and operators (protocol revenue).
- We were using Lido’s internal contract shares as `OutputTokenSupply`. The number of shares is not the supply of stETH. **Fixed that too.**

Solves this: #1453

Syncing here (name is saddle-finance because of reusing eth deployments): https://okgraph.xyz/?q=Qmd13EkC2ksj4ETcnSpJfncorf4ynfwyK7UUTkHrxiL4hY

### CODE REVIEW

**Comment by dmelotik** [comment]
> name is saddle-finance because of reusing eth deployments

@jaimehgb you can acutally create new ethereum hosted service subgraphs..

**Comment by jaimehgb** [comment]
> > name is saddle-finance because of reusing eth deployments
> 
> @jaimehgb you can acutally create new ethereum hosted service subgraphs..

Oh really? 😅 
I thought it had been deprecated?

**Review by dmelotik — APPROVED** [review]
nice update! lgtm

**Comment by jaimehgb** [comment]
@bye43 can you take a quick glance at this Lido version?
Relevant changes are:
- Fixing hourly snapshots (they were only appearing in 24h intervals)
- Refactor of revenue calculation (but should have the same values)
- Changes to `outputTokenSupply`, before it was tracking internal contract shares. Now it tracks stETH supply

https://thegraph.com/hosted-service/subgraph/jaimehgb/saddle-finance (it has a pending version, but it is exactly the same as the main one. Depends on when you get to review this it might still be syncing or not. In any case, using the current version will give the same result)

**Comment by bye43** [comment]
@jaimehgb This looks good to go!

**Pull request merged**
