### PR TITLE
Functioning initial Tectonic Subgraph

### PR DESCRIPTION
**Pull request by BenReilly19**

### CODE REVIEW

**Review by dmelotik — COMMENTED** [review]
Looks really nice and clean

Only thing missing is the rewards.

Once that is added LGTM

**Comment by this-username-is-taken** [comment]
@BenReilly19 let us know if this is ready

**Comment by BenReilly19** [comment]
@this-username-is-taken This pull is ready to be merged. Working on Rewards now will send another PR after that is added, or you can cancel this and I will PR again once rewards are functioning. Up to you.

**Comment by this-username-is-taken** [comment]
oh i see. Feel free to continue off this PR then

**Pull request closed without merging**
