### PR TITLE
fix(#patch); dforce; fix emssion/rates for dforce-optimism

### PR DESCRIPTION
**Pull request by tnkrxyz**
This PR will fix 0 reward APR issue reported in dforce QA #1138  by @ishraq8 

It borrows rewards.ts from rari-fuse (another compound-forks) to calculate blocks per day dynamically, but atm the number seems too high at 320991 for optimism (~3.7 blocks/seconds): https://api.thegraph.com/subgraphs/name/tnkrxyz/dforce-optimism/graphql?query=%7B%0A++circularBuffers%7B%0A++++blocksPerDay%0A++++bufferSize%0A++++blocks%0A++%7D%0A%7D

And this leads to high rewardAPR and rates at 64%/126% andd 226%/171%:
https://subgraphs.messari.io/subgraph?endpoint=https%3A%2F%2Fapi.thegraph.com%2Fsubgraphs%2Fname%2Ftnkrxyz%2Fdforce-optimism&tab=pool&poolId=0x7e7e1d8757b241aa6791c089314604027544ce43&view=marketHourlySnapshots-rewardAPR

https://subgraphs.messari.io/subgraph?endpoint=https%3A%2F%2Fapi.thegraph.com%2Fsubgraphs%2Fname%2Ftnkrxyz%2Fdforce-optimism&tab=pool&poolId=0x7e7e1d8757b241aa6791c089314604027544ce43&view=marketHourlySnapshots-rates

@dmelotik I appreciate it if you can help review my changes and see what I did incorrectly. I am not following the logic in `getRewardsPerDay()` (I didn't make any changes to it.)

### CODE REVIEW

**Comment by dmelotik** [comment]
> I am not following the logic in getRewardsPerDay() (I didn't make any changes to it.)

With the changes I am suggesting you can simply just get rewards/block and multiply by blocks per day to get the `emissionSupply` and `emmissionBorrow`.

**Comment by dmelotik** [comment]
Polygon is consistent enough that I think you can also hardcode the blocks/sec: https://polygonscan.com/chart/blocktime

**Comment by tnkrxyz** [comment]
OK, I set OPTIMISM_BLOCKS_PER_YEAR = ETHEREUM_BLOCKS_PER_YEAR; MATIC_BLOCKS_PER_YEAR is set to SECONDS_PER_YEAR / 2 in compound-forks/src/constants (=2 seconds/block)

**Review by dmelotik — APPROVED** [review]
Nice job 🚀

**Pull request merged**
