### PR TITLE
refactor(#major); multichain; add deployment networks, only use eventHandlers

### PR DESCRIPTION
**Pull request by dhruv-chauhan**
Deployments,

- Arbitrum: https://okgraph.xyz/?q=dhruv-chauhan%2Fmultichain-arbitrum
- Avalanche: https://okgraph.xyz/?q=dhruv-chauhan%2Fmultichain-avalanche
- BSC: https://okgraph.xyz/?q=dhruv-chauhan%2Fmultichain-bsc
- Celo: https://okgraph.xyz/?q=dhruv-chauhan%2Fmultichain-celo
- Ethereum: https://okgraph.xyz/?q=dhruv-chauhan%2Fmultichain-mainnet
- Fantom: https://okgraph.xyz/?q=dhruv-chauhan%2Fmultichain-fantom
- Gnosis: https://okgraph.xyz/?q=dhruv-chauhan%2Fmultichain-gnosis
- Optimism: https://okgraph.xyz/?q=dhruv-chauhan%2Fmultichain-optimism
- Polygon: https://okgraph.xyz/?q=dhruv-chauhan%2Fmultichain-polygon

### CODE REVIEW

**Comment by dhruv-chauhan** [comment]
@dmelotik yes, we do need this. There are some pricing issues I need to fix, which I would take up once I'm through with my existing work.

**Review by dmelotik — COMMENTED** [review]
Nice work @dhruv-chauhan !

We will need to make the deployments `dev` until they are QA'd, but for now I'd say we can leave it while the QA is happening. I will let the team know it is ready for QA

**Comment by dmelotik** [comment]
Can you rebase this so we can see what is being done? Looks weird now that other stuff got merged in

**Comment by dhruv-chauhan** [comment]
@dmelotik done rebasing :heavy_check_mark:

**Review by dmelotik — APPROVED** [review]
lgtm, all `prod` now

**Pull request merged**
