### PR TITLE
fix(#patch); arbitrum-one-bridge (ethereum); fixing inconsistent TVL for (spell) pool issue #2090

### PR DESCRIPTION
**Pull request by fortysevenlabs**
Issue Reference: #2090. This PR resolves inconsistent pool TVL (Spell Token) as a result of price inconsistencies stemming from Yearn for SPELL.

**Before commenting out Yearn:**

Pasted Graphic 3

Pasted Graphic

[See pool in subgraphs.messari.io](https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/messari/arbitrum-one-bridge-ethereum&tab=pool&poolId=0xa3a7b6f88361f48403514059f1f16c8e78d60eec090185f2135308bad17527004364ebcc2d37e5f6)

**After commenting out Yearn:**

Pasted Graphic 1

image

[See pool in subgraphs.messari.io](https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/id/QmRsTQmXsZHWY5FBeBNUQbMTVLXdaZKnYtqU1v3StvewiF&tab=pool&poolId=0xa3a7b6f88361f48403514059f1f16c8e78d60eec090185f2135308bad17527004364ebcc2d37e5f6)

### CODE REVIEW

**Comment by fortysevenlabs** [comment]
cc: @bye43 @dmelotik

**Review by dmelotik — APPROVED** [review]
LGTM

I am approving, but can you add a note to the readme explaining why we are not using the yearn oracle and link to the issue. Thanks!

**Comment by fortysevenlabs** [comment]
I'll add a README after 👍 on both ethereum (completed) and arbitrum (in-progress) side.

**Comment by dmelotik** [comment]
@fortysevenlabs are we still waiting for the subgraphs to sync?

**Comment by fortysevenlabs** [comment]
Syncing had finished but we pushed new changes for the arbitrum side which doesn't include this change.

Let's do this: I'll create a new PR which will include these changes (1 and 2 are already on the same branch):
1. arbitrum-side subgraph
2. support for ARB token
3. #2090

Then QA all of them together.

**Comment by dmelotik** [comment]
Accomplished in another PR

**Pull request closed without merging**
