### PR TITLE
feat(#minor); optimism-bridge-v2; Upgrade to 1.2 schema

### PR DESCRIPTION
**Pull request by spitko**
https://okgraph.xyz/?q=spitko%2Foptimism-bridge-v2-optimism
https://okgraph.xyz/?q=spitko%2Foptimism-bridge-v2-ethereum

### CODE REVIEW

**Review by dmelotik — COMMENTED** [review]
Thanks for updating this @spitko !

What about `totalValueImported` on ethereum?

**Comment by jaimehgb** [comment]
> What about `totalValueImported` on ethereum?

Unless you can bridge native optimism tokens to mainnet it is correct if it is 0.

Value imported / exported refers to the value of foreign tokens currently liquid in the chain, and the value of this chain native tokens currently liquid abroad respectively.

**Comment by dmelotik** [comment]
@jaimehgb if there is value exported from optimism, wouldn't that mean there should be value imported on ethereum?

**Comment by spitko** [comment]
> @jaimehgb if there is value exported from optimism, wouldn't that mean there should be value imported on ethereum?

Yes it would. But in the case of Optimism Gateway, it is not possible to transfer any optimism native tokens to ethereum network. Which is why the TVL and exported value are both 0 on optimism.

**Comment by dmelotik** [comment]
oops, I thought optimism has a TVE. All good

**Pull request merged**
