### PR TITLE
Add Event Interface to Generic Schema

### PR DESCRIPTION
**Pull request by Data-Nexus**
Added an Event Interface to the Generic Schema.

Protocols typically have a set of events that would useful to display to users to see an activity feed for the protocol, a market or their account. Each protocol may have varying events, but they can be standardly queried using an Event interface and using __typename to return the event type.

Below is a sample query would accomplish this: 
```
query UserEventLog($skip: Int = 0, $first: Int = 10, $account: String = "0x0xabc123") {
  events(first: $first, skip: $skip, where: {account: $account}) {
    hash
    timestamp
    account {
      id
    }
    amount
    market {
      id
      name
    }
    __typename
  }
}
```

### CODE REVIEW

**Comment by dmelotik** [comment]
@Data-Nexus is this an example or are you proposing this gets added to the generic schema?

**Comment by Data-Nexus** [comment]
I am proposing that we add this as a standard feature in the schema. Each protocol will vary in the events they emit, but as developers start planning how they're going to tackle their mapping they should incorporate this in their building plan.

**Comment by dmelotik** [comment]
@Data-Nexus, this will be our best place to keep track of this as we go through issues regularly https://github.com/messari/subgraphs/issues/1658

**Comment by dmelotik** [comment]
I am going to close with the previous comment in mind.

**Pull request closed without merging**
