### PR TITLE
fix(); Compound forks; use getMarket(Hourly/Daily)SnapshotID function

### PR DESCRIPTION
**Pull request by 0xbe1**

### CODE REVIEW

**Comment by this-username-is-taken** [comment]
nice catch!

**Comment by dmelotik** [comment]
@0xbe1 this should either be #patch and change and increment the version or nothing in (), but the change lgtm.

**Review by dmelotik — CHANGES_REQUESTED** [review]
changes req

**Comment by 0xbe1** [comment]
@dmelotik updated pr description

**Pull request merged**
