### PR TITLE
Maker DAO: Schema 1.3.0 update

### PR DESCRIPTION
**Pull request by harsh9200**

### CODE REVIEW

**Comment by this-username-is-taken** [comment]
Great job!

**Comment by tnkrxyz** [comment]
@harsh9200 , have you tried deploying the updated makerdao subgraph? My deployment failed with an error (https://thegraph.com/hosted-service/subgraph/tnkrxyz/makerdao-ext?selected=logs):

```
Subgraph failed with non-deterministic error: failed to process trigger: block #8928171 (0x67e4…0d7b), transaction 9d2e1b5b30b629c6cf547ed86fcbd8d71e4eab63a3ac7c982b1ae394dbf7385e: Entity LendingProtocol[0x35d1b3f3d7966a1dfe207aa4514c12a259a0492b]: missing value for non-nullable field `cumulativeSupplySideRevenueUSD`\twasm backtrace:\t    0: 0x44ae - <unknown>!generated/schema/LendingProtocol#save\t    1: 0x47cf - <unknown>!src/common/getters/getOrCreateLendingProtocol\t    2: 0x4b8b - <unknown>!src/common/metrics/updateUsageMetrics\t    3: 0x5075 - <unknown>!src/mappings/users/users/handleCreated\t, retry_delay_s: 120, attempt: 0
```

**Comment by harsh9200** [comment]
@tnkrxyz, I deployed the latest `Maker DAO` subgraph code on hosted service, It is working fine for me (https://thegraph.com/hosted-service/subgraph/harsh9200/makerdao?selected=logs). are you sure you are using the latest code? 

And yes, I see the non-null warnings, I will create a PR for those warnings.

**Comment by tnkrxyz** [comment]
@harsh9200 thanks for looking into this.

Oddly, I am getting the same deployment failure even with fresh codebase cloned off the messari/subgraphs master branch. Let me check with @steegecs if he still experiences deployment failure.

I also have to fix some mixing of upper/lower case names before I can run 'graph codegen' on the subgraph. For example, "abis/ERC20.json" is in upper case, but in subgraph.yaml, it is referred as "./abis/erc20.json" (lower case).

**Comment by tnkrxyz** [comment]
The different results we got is due to version difference of graph-cli. Mystery solved.

**Pull request merged**
