### PR TITLE
Address Arrakis QA issues

### PR DESCRIPTION
**Pull request by l0c4t0r**
Partially addresses QA issues in #587 .

1.  Improved vault naming by adding fee tier suffix to vault name.
2. Yearn Lens was giving bad pricing data for FEI ($0.35 vs $1), skip Yearn Lens for FEI when getting prices.

This fixes the TVL for the vault with the greatest disparity.  There are still some differences in TVL values vs those reported  by Arrakis for smaller vaults that account for ~0.1% of Arrakis total TVL.  I have no address these in this PR as these are due to more systematic issues around how we update TVL, and price lib support.  I elaborate on these in #587

### CODE REVIEW

**Comment by l0c4t0r** [comment]
Deployed at l0c4t0r/laboratory4 for verification.

**Comment by this-username-is-taken** [comment]
Would you be able to change this to true so it'll auto-deploy?
https://github.com/messari/subgraphs/blob/fc9a2936ba7289aecd6d867301ff599a1ab6e1e0/deployment/deployment.json#L241

**Comment by l0c4t0r** [comment]
Done!

**Comment by this-username-is-taken** [comment]
Thanks for the fix!

**Pull request merged**
