### PR TITLE
feat(#major); aave v3; add aave v3 ethereum

### PR DESCRIPTION
**Pull request by dmelotik**
Test: https://okgraph.xyz/?q=messari%2Faave-v3-ethereum

### CODE REVIEW

**Comment by dmelotik** [comment]
@ishraq8 could you make a QA on this next week?

**Comment by ishraq8** [comment]
@dmelotik Forget next week, looked through the subgraph. Everything looks great and makes sense. It is hard to assess the stable APR rate but it seems to be reasonable. Also front end shows WETH & ETH, but both are separate pools

Only issue, all markets showing up as Not active
Screen Shot 2023-01-27 at 10 38 19 PM

**Comment by ishraq8** [comment]
QA issues resolved just need code review.

**Review by tnkrxyz — APPROVED** [review]
lgtm. approved.
I will add ethereum to the refactored aave v3 after I address your comments.

**Pull request merged**
