### PR TITLE
Update Compound/forks to 1.3.0

### PR DESCRIPTION
**Pull request by dmelotik**
Updating Compound v2 / compound-forks to schema 1.3.0

Compound fork test: https://thegraph.com/hosted-service/subgraph/dmelotik/bastion-protocol?version=pending / https://okgraph.xyz/?q=dmelotik%2Fbastion-protocol

Compound-v2: https://okgraph.xyz/?q=QmNQdqoFddCLveRTFpP6s1AgdowouYodqqBfST8yHdiUB5

- [x] Update once https://github.com/messari/subgraphs/pull/331 is in master
- [x] add this change too https://github.com/messari/subgraphs/pull/330

### CODE REVIEW

**Comment by this-username-is-taken** [comment]
This is great! Would you be able to incorporate these as well: https://github.com/messari/subgraphs/pull/330

**Comment by this-username-is-taken** [comment]
and this: https://github.com/messari/subgraphs/pull/331

**Comment by tnkrxyz** [comment]
I am hoping #317 can be merged before the schema upgraded to 1.3.0

**Comment by this-username-is-taken** [comment]
Would you be able to merge `compound-v2` into `compound-forks` (i.e. add it as a fork)? It will make things easier to maintain going forward?

**Comment by this-username-is-taken** [comment]
Great work 🔥

**Pull request merged**
