### PR TITLE
fix(#minor); Balancer Forks; Fix mainnet deployment TVL spike 

### PR DESCRIPTION
**Pull request by harsh9200**
Fixes: #1925

### CODE REVIEW

**Review by dmelotik — COMMENTED** [review]
code lgtm, but can you add your test deployments?

- let's make the graft false for now. imo it is preffered to leave it off in master and configure as needed.
- Also is this issue also related? https://discord.com/channels/953684103012683796/1046922440846098492/1090841930767798368

**Comment by harsh9200** [comment]
@dmelotik 
Test Deployment: [Link](https://thegraph.com/hosted-service/subgraph/messari/balancer-v2-ethereum)

- I have turned off grafting. 
- yes, balancer v2 TVL bug is related to this PR.

**Comment by dmelotik** [comment]
@harsh9200 looks like it crashed

**Comment by harsh9200** [comment]
yes, sorry this is the correct deployment URL's.

Balancer: [Mainnet](https://thegraph.com/hosted-service/subgraph/harsh9200/balancer-v2-mainnet?version=pending), [Arbitrum](https://thegraph.com/hosted-service/subgraph/harsh9200/balancer-v2-arbitrum), [Polygon](https://thegraph.com/hosted-service/subgraph/harsh9200/balancer-v2-polygon)

Beethoven: [Optimism](https://thegraph.com/hosted-service/subgraph/harsh9200/beethoven-optimism), [Fantom](https://thegraph.com/hosted-service/subgraph/harsh9200/beethoven-x-fantom)

**Comment by dmelotik** [comment]
@harsh9200 is the $425bb spike on balancer mainnet expected?

**Comment by harsh9200** [comment]
@dmelotik  No, that's not expected. I am already working on a fix.

**Comment by harsh9200** [comment]
Addressed in #2116.

**Pull request closed without merging**
