### PR TITLE
chore(); deployment.json; Set dexes to prod that are prod ready in deployment.json

### PR DESCRIPTION
**Pull request by steegecs**
**Context:**
Set: 
- Pangolin
- Solarbeam
- mm finance
- VVS Finance

To `prod` in deployment.json.

### CODE REVIEW

**Comment by this-username-is-taken** [comment]
@steegecs is pangolin prod-ready? I see there is still an issue open for it: https://github.com/messari/subgraphs/issues/1230

**Comment by this-username-is-taken** [comment]
also, what's the status on Uniswap v3? I thought some of them are prod ready

**Comment by pietydespises** [comment]
Spiritswap could most likely be added to this

**Comment by steegecs** [comment]
@pietydespises I think so too, since we've just decided. 
@this-username-is-taken All Uniswap V3 have been validated so they should all be `prod`. Pangolin should not. 

Addressing here -- > https://github.com/messari/subgraphs/pull/1286

**Pull request merged**
