### PR TITLE
fix (#minor); goldfinch-ethereum; fixing subgraph indexing error

### PR DESCRIPTION
**Pull request by tnkrxyz**
This PR fixes goldfinch subgraph indexing error reported in #2115 

### deployment and dashboard
- deployment: https://thegraph.com/hosted-service/subgraph/tnkrxyz/goldfinch-ethereum?selected=logs
- dashboard: https://subgraphs.messari.io/subgraph?endpoint=https://api.thegraph.com/subgraphs/name/tnkrxyz/goldfinch-ethereum&tab=protocol

Note: eslint no-magic-number rule is disabled for code from goldfinch's official subgraph

### CODE REVIEW

**Comment by dmelotik** [comment]
@tnkrxyz can you point me to where this is in the code? https://github.com/messari/subgraphs/issues/2115#issuecomment-1557595469

That is the piece I am most concerned about

**Review by dmelotik — COMMENTED** [review]
Can you just add a note in the readme of what we needed to do in order to add that pool in? In case we run into the issue again and need to fix.

Otherwise looks good! I know we are mostly just copying what goldfinch has here, but it fixes the issue, and the data looks more or less the same + the missing pool is there.

**Comment by tnkrxyz** [comment]
> @tnkrxyz can you point me to where this is in the code? [#2115 (comment)](https://github.com/messari/subgraphs/issues/2115#issuecomment-1557595469)
> 
> That is the piece I am most concerned about

responded to the comment in the issue.

**Comment by tnkrxyz** [comment]
> @tnkrxyz Can you just add a note in the readme of what we needed to do in order to add that pool in? In case we run into the issue again and need to fix.
> 
> Otherwise looks good! I know we are mostly just copying what goldfinch has here, but it fixes the issue, and the data looks more or less the same + the missing pool is there.

added description for the new CallableLoan contract in [c299154](https://github.com/messari/subgraphs/pull/2195/commits/c2991540a00e4550984ea4bf818943f4ac97620b). Is it sufficient?

**Review by dmelotik — APPROVED** [review]
lgtm thanks @tnkrxyz ! We will wait for the final QA 👍 from @ishraq8 before merging

**Comment by dmelotik** [comment]
hosting 🤖

**Pull request merged**
