### PR TITLE
fix(#patch); uniswap-forks; add broken ERC20 tokens

### PR DESCRIPTION
**Pull request by dhruv-chauhan**
Some of the uniswap deployments are failing with `message: overflow converting 0x... to i32` inside `getOrCreateToken()` method.
Examples of such tokens are: [token 1](https://optimistic.etherscan.io/address/0x000000000000be0ab658f92dddac29d6df19a3be) and [token 2](https://etherscan.io/address/0x0000000000bF2686748E1C0255036e7617E7E8A5)

---

Inside `getOrCreateToken()` method, we try to bind token's address to ECR20 abi. For the above listed tokens, this `ERC20.bind(tokenAddr)` fails, since these tokens have unverified contracts with do not adhere to ERC20 standard.
 
Since there does not exist something like `try_bind()` and `try...catch` is not implemented yet for assemblyscript, we are keeping a list of these brokenERC20 tokens in network configs.

---

Deployments, 

- https://okgraph.xyz/?q=dhruv-chauhan%2Funiswap-v3-optimism
- https://okgraph.xyz/?q=dhruv-chauhan%2Funiswap-v2-swap-ethereum

### CODE REVIEW

**Review by steegecs — COMMENTED** [review]
Looks good! It looks like you are missing the updates to the configurations.ts for the Uniswap V3 and Sushiswap V3 subgraphs in the `uniswap-v3-forks-swap` folder.

**Comment by dhruv-flameshot** [comment]
@steegecs added!

**Comment by dhruv-chauhan** [comment]
@steegecs added ✅

**Review by steegecs — APPROVED** [review]
LGTM!

**Pull request merged**
