### PR TITLE
chore(); moonwell; add grafting

### PR DESCRIPTION
**Pull request by dhruv-chauhan**

### CODE REVIEW

**Review by dmelotik — APPROVED** [review]
nice find

**Comment by rahul7668gupta** [comment]
Hi, it looks like I am also facing the same issue and am unable to fix it seeing the file changes in this pr.
I added 
```
  "graftEnabled": true,
  "subgraphId": "QmYGirbB111UXkresB2u7AmsycUNvLfWd2GDb2uFfMxW7W",
  "graftStartBlock": 14667562
```
to my networks.json

and 
```
{{#graftEnabled}}
features:
  - grafting
graft:
  base: {{subgraphId}} # Subgraph ID of base subgraph
  block: {{graftStartBlock}} # Block number
{{#graftEnabled}}
```
to my subgraph.yaml 

Is there anything more I need to do in order to fix this issue on my subgraph? 
My subgraph is on ethereum mainnet.

**Comment by dhruv-chauhan** [comment]
If you're adding grafting config directly to your subgraph.yaml, you do not need to use mustache templating. You can instead just add snippet,
```
features:
  - grafting
graft:
  base: "QmYGirbB111UXkresB2u7AmsycUNvLfWd2GDb2uFfMxW7W"
  block: 14667562
```
@rahul7668gupta

**Comment by rahul7668gupta** [comment]
Yeah, so I see grafting uses existing data from an already deployed subgraph and then syncs after that. 

My subgraph is failing immediately some blocks after deployment. 

I am not sure grafting is the correct way to fix it, but that is what I have been able to find on the GitHub issues till now.

**Pull request merged**
